### ISSUE TITLE
opam install base_bigstring -> compilation termniated endian.h on DragonFly BSD 5.8.1

### ISSUE THREAD

**Issue by msgoff** [janestreet/base_bigstring#1]
endian.h compiler error. 
I spent a couple of hours trying to resolve the issue with no luck.
strace shows No such file when looking for ocplib-endian which exists on my system but not in the same place.

I have tried the include flag with gcc to look for endian.h and that also did not help.
I am willing to do the work to troubleshoot the issue if you have some ideas on what a good next step might be.

If you ned additional env variables, logs, or results from specific commands, please let me know.

[base_bigstring-826-58c514_out.txt](https://github.com/janestreet/base_bigstring/files/5227354/base_bigstring-826-58c514_out.txt)
[base_bigstring-826-58c514_info.txt](https://github.com/janestreet/base_bigstring/files/5227355/base_bigstring-826-58c514_info.txt)
[base_bigstring-826-58c514_env.txt](https://github.com/janestreet/base_bigstring/files/5227356/base_bigstring-826-58c514_env.txt)

**Comment by hhugo** [comment]
Have you tried replacing
``` 
#if defined(__FreeBSD__) || defined(__NetBSD__) || defined(__OpenBSD__)
#include <sys/endian.h>
#else
```
by
``` 
#if defined(__FreeBSD__) || defined(__NetBSD__) || defined(__OpenBSD__) || defined(__DragonFly__)
#include <sys/endian.h>
#else
```
in https://github.com/janestreet/base_bigstring/blob/master/src/base_bigstring_stubs.c ?

**Comment by msgoff** [comment]
That solved the issue.
Thank you!
