### ISSUE TITLE
compilation fails under mingw

### ISSUE THREAD

**Issue by mroch** [janestreet/base_bigstring#2]
I'm trying to compile this package on Windows using the stock opam-repository instead of opam-repository-mingw, and it fails trying to `#include <endian.h>`.

it would be great if this patch was upstreamed!

https://github.com/fdopen/opam-repository-mingw/blob/65d4525f0f0d6e6763ad41feb825479e1537d5db/packages/base_bigstring/base_bigstring.v0.14.0/files/base_bigstring-v0.14.0.patch

cc @fdopen

**Comment by Chimrod** [comment]
Hello, do you have any update on this issue ?

**Comment by dkalinichenko-js** [comment]
We're on it, will be included in the next release.
